# --destination ~/Development/SIGCSE/_site
# destination: /Users/mapq/Development/SIGCSE/_site
title: SIGCSE
email: webmaster@sigcse.org
description: >-
  ACM SIGCSE group, special interest group in computer science education

# For Deployment (live)
baseurl: "" # the subpath of your site, e.g. /blog


# The base hostname & protocol for your site
url: "https://sigcse.org" 

exclude: ["Gemfile", "Gemfile.lock", "_documentation", "_pending", "_unused", "bin"]
keep_files: ["assets"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

permalink: /about/news/:year-:month-:title:output_ext

# long sequence of numbers to make loop go for a while, contents
# of colletion is irrelevant
breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

